# database.pandas_gbq
> extract data from database (BigQuery) with pandas GBQ

In [1]:
#| default_exp data.database.pandas_gbq

In [2]:
#| hide
from nbdev.showdoc import *

In [3]:
#| hide
import nbdev; nbdev.nbdev_export()

In [4]:
#| hide
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [5]:
#| hide
from google.cloud import bigquery
from dotenv import load_dotenv
import os

In [6]:
#| export
import pandas_gbq
import pandas as pd
from google.oauth2 import service_account
from google.oauth2.service_account import Credentials

In [7]:
#| export

In [8]:
# os.environ

In [9]:

load_dotenv("../.env")

True

In [10]:
os.environ

environ{'GSM_SKIP_SSH_AGENT_WORKAROUND': 'true',
        'LC_ALL': 'en_US.UTF-8',
        'WINDOWPATH': '2',
        'PATH': '/home/x/.pyenv/versions/miniforge3-latest/envs/prc/bin:/home/x/.pyenv/versions/miniforge3-latest/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin',
        'CONDA_PREFIX': '/home/x/.pyenv/versions/miniforge3-latest/envs/prc',
        'LIBVIRT_DEFAULT_URI': 'qemu:///system',
        'LOGNAME': 'x',
        'XDG_CONFIG_DIRS': '/etc/xdg/xdg-cinnamon:/etc/xdg',
        'XAUTHORITY': '/run/user/1000/gdm/Xauthority',
        'XDG_SESSION_ID': '2',
        'CONDA_SHLVL': '1',
        'XMODIFIERS': '@im=ibus',
        'GIO_LAUNCHED_DESKTOP_FILE_PID': '6794',
        'GIO_LAUNCHED_DESKTOP_FILE': '/home/x/Desktop/pycharm.desktop',
        'QT_ACCESSIBILITY': '1',
        'CONDA_DEFAULT_ENV': 'prc',
        'XDG_SEAT': 'seat0',
        'XDG_VTNR': '2',
        'QTWEBENGINE_DICTIONARIES_PATH': '/usr/share/hunspell-bdic/',
        'XDG_SESSION_DESKTOP': 'cinnamon',
        'DBUS_SESSION_BUS_ADDRESS': 'unix:path=/run/user/1000/bus',
        'CONDA_PROMPT_MODIFIER': '(prc) ',
        'USERNAME': 'x',
        'SHLVL': '0',
        'XDG_DATA_DIRS': '/usr/share/gnome:/usr/share/cinnamon:/usr/share/gnome:/home/x/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop',
        'SHELL': '/usr/bin/zsh',
        'PYTHONPATH': '/home/x/projects/pricing',
        'GTK_IM_MODULE': 'ibus',
        'SESSION_MANAGER': 'local/l:@/tmp/.ICE-unix/4211,unix/l:/tmp/.ICE-unix/4211',
        'XDG_SESSION_CLASS': 'user',
        'GTK_MODULES': 'gail:atk-bridge',
        'DISPLAY': ':1',
        'HOME': '/home/x',
        'XDG_CURRENT_DESKTOP': 'X-Cinnamon',
        'DEBUGINFOD_URLS': 'https://debuginfod.ubuntu.com ',
        'QT_IM_MODULE': 'ibus',
        'LANG': 'en_US.UTF-8',
        'GDMSESSION': 'cinnamon',
        'GNOME_DESKTOP_SESSION_ID': 'this-is-deprecated',
        'CLUTTER_IM_MODULE': 'ibus',
        'GTK3_MODULES': 'xapp-gtk3-module',
        'LANGUAGE': '',
        'SSH_AUTH_SOCK': '/run/user/1000/keyring/ssh',
        'XDG_RUNTIME_DIR': '/run/user/1000',
        'GDAL_DATA': '/home/x/.pyenv/versions/miniforge3-latest/envs/prc/share/gdal',
        'GPG_AGENT_INFO': '/run/user/1000/gnupg/S.gpg-agent:0:1',
        'DESKTOP_SESSION': 'cinnamon',
        'USER': 'x',
        'XDG_SESSION_TYPE': 'x11',
        'PWD': '/home/x/projects/pricing',
        'JPY_SESSION_NAME': 'nbs/01.data.database.pandas_gbq.ipynb',
        'JPY_PARENT_PID': '8326',
        'PYDEVD_USE_FRAME_EVAL': 'NO',
        'TERM': 'xterm-color',
        'CLICOLOR': '1',
        'FORCE_COLOR': '1',
        'CLICOLOR_FORCE': '1',
        'PAGER': 'cat',
        'GIT_PAGER': 'cat',
        'MPLBACKEND': 'module://matplotlib_inline.backend_inline',
        'GC_QUOTE_API_CREDENTIALS': 'res/quote-api-365206-39d39b2fde07.json',
        'GC_TEST_API_CREDENTIALS': 'res/elife-data-warehouse-test-fe5c09d48a87.json',
        'HTTP_PROXY': 'http://127.0.0.1:20171',
        'HTTPS_PROXY': 'http://127.0.0.1:20171'}

In [ ]:
# os.getenv('GC_QUOTE_API_CREDENTIALS')
# os.getenv('HTTP_PROXY')
# os.getenv('HTTPS_PROXY')

In [16]:
# config = dotenv_values("../.env")
# key = config.get('GC_QUOTE_API_CREDENTIALS')
key = os.getenv('GC_QUOTE_API_CREDENTIALS')

In [21]:
credential = service_account.Credentials.from_service_account_file("../" + key)

In [43]:

key_test = os.getenv('GC_TEST_API_CREDENTIALS')
credential_test = service_account.Credentials.from_service_account_file("../" + key_test)
client_test = bigquery.Client(credentials=credential_test)

QUERY = """
    select 'start', 'end' 
    from `elife-data-warehouse-test.price.fixed_zone_routes`
    limit 10
    """

df = pandas_gbq.read_gbq(QUERY, credentials=credential_test)
df.head()

Downloading: |          |

Empty DataFrame
Columns: [f0_, f1_]
Index: []

In [34]:
# QUERY = """
# 	select
# 		*
# 	from `elife-data-warehouse-test.price.fixed_zone_routes `
# 
#     """
# 
# df = pandas_gbq.read_gbq(QUERY)

In [ ]:

#os.environ['HTTP_PROXY'] = "http://127.0.0.1:20171"
#os.environ['HTTPS_PROXY'] = "http://127.0.0.1:20171"
#os.environ['http_proxy'] = "http://127.0.0.1:20171"
#os.environ['https_proxy'] = "http://127.0.0.1:20171"

In [ ]:
os.environ

In [18]:
client = bigquery.Client(credentials=credential)

QUERY = """
		select *
		from `quote-api-365206.report.ride_dispatch_v` r
		where dispatch_amount_net_usd is not null
        limit 20
		"""

In [ ]:

# query_job = client.query(QUERY)

In [19]:

df = pandas_gbq.read_gbq(QUERY,credentials=credential)

Downloading: 100%|██████████|

In [20]:
df.head()

,ride_id,trip_no,dispatch_id,trip_type,ride_stat,dispatch_stat,partner_tran_id,partner_id,from_fleet_id_as_customer,pickup_date,...,has_complaint,has_fleet_complaint,has_penalty_complaint,has_ops_complaint,gps_ad_check,gps_cns_check,score,incoming_dispatch_info_last_updated_at,dispatch_info_last_updated_at,etl_time
0,2406794,0,534711,None,Accepted,At destination,245332,1,16,2022-12-27,...,1,0,1,1,0,0,None,2023-01-13 18:15:10+00:00,2023-01-13 18:15:10+00:00,2024-09-27 00:15:04.396655+00:00
1,3531231,1,2800358,point2point,Cancelled,Accepted,1377216,1,16,2024-06-30,...,0,0,0,0,0,0,None,2024-06-13 13:12:21+00:00,2024-06-13 14:10:50+00:00,2024-09-27 00:15:04.396655+00:00
2,2191163,1,56349,None,Cancelled,Accepted,27768,1,16,2021-09-09,...,0,0,0,0,0,0,None,2021-09-05 13:22:30+00:00,2021-09-05 13:22:31+00:00,2024-09-27 00:15:04.396655+00:00
3,2371574,1,456881,None,Accepted,Accepted,209606,1,16,2022-12-04,...,1,1,0,0,0,0,None,2022-12-02 15:33:10+00:00,2022-12-02 21:50:22+00:00,2024-09-27 00:15:04.396655+00:00
4,2398953,1,518874,None,Accepted,Customer no show,237411,1,16,2022-11-27,...,0,0,0,0,0,0,None,2022-11-24 09:28:34+00:00,2022-12-15 06:24:05+00:00,2024-09-27 00:15:04.396655+00:00

In [ ]:
QUERY = """
		select *
		from elife-data-warehouse-prod.ods.ride_ride as t0 
        limit 20
		"""

In [ ]:

# df = pandas_gbq.read_gbq(QUERY,credentials=credential)

In [ ]:
# df.head()

In [ ]:
QUERY = """
		select
		    t0.id as ride_id,
		    t1.id as dispatch_id,
            CASE
                WHEN t2.trip_no = t1.trip_no THEN t2.trip_type
                ELSE NULL
            END AS trip_type_id,
		    ARRAY_TO_STRING(ARRAY(
		        SELECT
                    t3.name
                FROM
                    elife-data-warehouse-prod.ods.ride_enum 
                    AS t3
                    WHERE t3.id = t2.trip_type AND t2.trip_no = t1.trip_no
            ), ',') AS trip_type,
		    t1.trip_no,
		    t0.stat AS ride_status_id,
		    ARRAY_TO_STRING(ARRAY(
		        SELECT
                    t3.name
                FROM
                    elife-data-warehouse-prod.ods.ride_enum 
                    AS t3
                    WHERE t3.id = t0.stat
            ), ',') AS ride_status,
            CASE
                WHEN t3.id = t0.partner_tran_id THEN t3.partner_id
                ELSE NULL
            END AS partner_id,
		    t0.from_time_str,
		    t0.from_timezone_str,
		    t0.to_time_str,
		    t0.to_timezone_str,
		    t0.from_place_id,
		    ARRAY_TO_STRING(ARRAY(
		        SELECT
                    t1.name
                FROM
                    elife-data-warehouse-prod.ods.ride_place
                    AS t1
                    WHERE t1.id = t0.from_place_id
            ), ',') AS from_place,
		    t0.to_place_id,
		    ARRAY_TO_STRING(ARRAY(
		        SELECT
                    t1.name
                FROM
                    elife-data-warehouse-prod.ods.ride_place
                    AS t1
                    WHERE t1.id = t0.to_place_id
            ), ',') AS to_place,
		    t0.distance,
		    t0.duration,
		    ARRAY_TO_STRING(ARRAY(
		        SELECT
                    t1.name
                FROM
                    elife-data-warehouse-prod.ods.ride_vehicle_class
                    AS t1
                    WHERE t1.id = t0.vehicle_class_id
            ), ',') AS vehicle_class,
		    t0.vehicle_class_id,
		    t0.passenger_count,
		    t0.luggage_count,
		    t0.trip_count,
		    t0.children_count,
		    t0.infant_count,
		    t1.amount as dispatch_amount,
		    t1.currency as dispatch_currency,
		    
		FROM 
            elife-data-warehouse-prod.ods.ride_ride AS t0 
            JOIN elife-data-warehouse-prod.ods.ride_dispatch AS t1 ON t0.id = t1.ride_id 
            LEFT JOIN elife-data-warehouse-prod.ods.ride_trip AS t2 ON t0.id = t2.ride_id 
            LEFT JOIN elife-data-warehouse-prod.ods.ride_partner_tran AS t3 ON t0.partner_tran_id = t3.id
        WHERE
            from_time_str > '2024-01-01'
        LIMIT
            10
		"""

In [ ]:

#df = pandas_gbq.read_gbq(QUERY,credentials=credentials)

In [ ]:
#| export
QUERY_PRICING_TRAINING = """
        WITH
        TripTypeID AS (
            SELECT
                t1.ride_id,
                CASE
                    WHEN t2.trip_no = t1.trip_no THEN t2.trip_type
                    ELSE NULL
                END AS trip_type_id,
            FROM
                elife-data-warehouse-prod.ods.ride_dispatch AS t1
                JOIN elife-data-warehouse-prod.ods.ride_trip AS t2 ON t1.ride_id = t2.ride_id
        ),
        TripType AS (
            SELECT
                t1.ride_id,
                t1.trip_type_id,
                t2.name AS trip_type,
            FROM
                TripTypeID AS t1
                LEFT JOIN elife-data-warehouse-prod.ods.ride_enum AS t2 ON t1.trip_type_id = t2.id
        ),
        RideStatus AS (
            SELECT
                t1.id AS ride_id,
                t1.stat AS ride_status_id,
                t2.name AS ride_status,
            FROM
                elife-data-warehouse-prod.ods.ride_ride AS t1
                LEFT JOIN elife-data-warehouse-prod.ods.ride_enum AS t2 ON t1.stat = t2.id
        ),
        PartnerID AS (
            SELECT
                t1.id AS ride_id,
                CASE
                    WHEN t2.id = t1.partner_tran_id THEN t2.partner_id
                    ELSE NULL
                END AS partner_id,
            FROM
                elife-data-warehouse-prod.ods.ride_ride AS t1
                LEFT JOIN elife-data-warehouse-prod.ods.ride_partner_tran AS t2 ON t1.partner_tran_id = t2.id
        ),
        Partner AS (
            SELECT
                t1.ride_id,
                t1.partner_id,
                t2.name AS partner,
            FROM
                PartnerID AS t1
                LEFT JOIN elife-data-warehouse-prod.ods.ride_partner AS t2 ON t1.partner_id = t2.id
        ),
        FromPlace AS (
            SELECT
                t1.id AS ride_id,
                t1.from_place_id as start_place_id,
                t2.name AS start_place,
                t2.lng AS longt,
                t2.lat AS latit,
            FROM
                elife-data-warehouse-prod.ods.ride_ride AS t1
                LEFT JOIN elife-data-warehouse-prod.dim.dim_place AS t2 ON t1.from_place_id = t2.id
        ),
        ToPlace AS (
            SELECT
                t1.id AS ride_id,
                t1.to_place_id as end_place_id,
                t2.name AS end_place,
                t2.lng AS longt,
                t2.lat AS latit,
            FROM
                elife-data-warehouse-prod.ods.ride_ride AS t1
                LEFT JOIN elife-data-warehouse-prod.dim.dim_place AS t2 ON t1.to_place_id = t2.id
        ),
        VehicleClass AS (
            SELECT
                t1.id AS ride_id,
                t1.vehicle_class_id as vehicle_class_id,
                t2.name AS vehicle_class,
            FROM
                elife-data-warehouse-prod.ods.ride_ride AS t1
                LEFT JOIN elife-data-warehouse-prod.ods.ride_vehicle_class AS t2 ON t1.vehicle_class_id = t2.id
        ),
        PricingTraining AS (SELECT t0.id       AS ride_id,
                                   t1.id       AS dispatch_id,
                                   t2.trip_type_id,
                                   t2.trip_type,
                                   t1.trip_no,
                                   t3.ride_status_id,
                                   t3.ride_status,
                                   t4.partner_id,
                                   t4.partner,
                                   t0.from_time_str,
                                   t0.from_timezone_str,
                                   t0.to_time_str,
                                   t0.to_timezone_str,
                                   t5.start_place_id,
                                   t5.start_place,
                                   t5.longt    AS start_longt,
                                   t5.latit    AS start_latit,
                                   t6.end_place_id,
                                   t6.end_place,
                                   t6.longt    AS end_longt,
                                   t6.latit    AS end_latit,
                                   t0.distance,
                                   t0.duration,
                                   t7.vehicle_class_id,
                                   t7.vehicle_class,
                                   t0.passenger_count,
                                   t0.luggage_count,
                                   t0.trip_count,
                                   t0.children_count,
                                   t0.infant_count,
                                   t1.amount   as dispatch_amount,
                                   t1.currency as dispatch_currency,

                            FROM `elife-data-warehouse-prod.ods.ride_ride` AS t0
                                     JOIN `elife-data-warehouse-prod.ods.ride_dispatch` AS t1 ON t0.id = t1.ride_id
                                     LEFT JOIN TripType AS t2 ON t0.id = t2.ride_id
                                     LEFT JOIN RideStatus AS t3 ON t0.id = t3.ride_id
                                     LEFT JOIN Partner AS t4 ON t0.id = t4.ride_id
                                     LEFT JOIN FromPlace AS t5 ON t0.id = t5.ride_id
                                     LEFT JOIN ToPlace AS t6 ON t0.id = t6.ride_id
                                     LEFT JOIN VehicleClass AS t7 ON t0.id = t7.ride_id
                            WHERE from_time_str > '2024-01-01'
        )

        SELECT
            t.ride_id,
            t.dispatch_id,
            t.trip_type,
            t.trip_no,
            t.ride_status,
            t.partner,
            t.from_time_str,
            t.from_timezone_str,
            t.to_time_str,
            t.to_timezone_str,
            t.start_place,
            t.start_latit,
            t.start_longt,
            t.end_place,
            t.end_latit,
            t.end_longt,
            t.distance,
            t.duration,
            t.vehicle_class,
            t.passenger_count,
            t.luggage_count,
            t.trip_count,
            t.children_count,
            t.infant_count,
            t.dispatch_amount,
            t.dispatch_currency,

        FROM
            PricingTraining AS t
        WHERE
            from_time_str > '2024-01-01'
        LIMIT
            200
"""

In [ ]:
#| export
QUERY_PRICING_TRAINING_FILTER = """
        WITH
        TripTypeID AS (
            SELECT
                t1.ride_id,
                CASE
                    WHEN t2.trip_no = t1.trip_no THEN t2.trip_type
                    ELSE NULL
                END AS trip_type_id,
            FROM
                elife-data-warehouse-prod.ods.ride_dispatch AS t1
                JOIN elife-data-warehouse-prod.ods.ride_trip AS t2 ON t1.ride_id = t2.ride_id
        ),
        TripType AS (
            SELECT
                t1.ride_id,
                t1.trip_type_id,
                t2.name AS trip_type,
            FROM
                TripTypeID AS t1
                LEFT JOIN elife-data-warehouse-prod.ods.ride_enum AS t2 ON t1.trip_type_id = t2.id
        ),
        RideStatus AS (
            SELECT
                t1.id AS ride_id,
                t1.stat AS ride_status_id,
                t2.name AS ride_status,
            FROM
                elife-data-warehouse-prod.ods.ride_ride AS t1
                LEFT JOIN elife-data-warehouse-prod.ods.ride_enum AS t2 ON t1.stat = t2.id
        ),
        PartnerID AS (
            SELECT
                t1.id AS ride_id,
                CASE
                    WHEN t2.id = t1.partner_tran_id THEN t2.partner_id
                    ELSE NULL
                END AS partner_id,
            FROM
                elife-data-warehouse-prod.ods.ride_ride AS t1
                LEFT JOIN elife-data-warehouse-prod.ods.ride_partner_tran AS t2 ON t1.partner_tran_id = t2.id
        ),
        Partner AS (
            SELECT
                t1.ride_id,
                t1.partner_id,
                t2.name AS partner,
            FROM
                PartnerID AS t1
                LEFT JOIN elife-data-warehouse-prod.ods.ride_partner AS t2 ON t1.partner_id = t2.id
        ),
        FromPlace AS (
            SELECT
                t1.id AS ride_id,
                t1.from_place_id as start_place_id,
                t2.name AS start_place,
                t2.lng AS longt,
                t2.lat AS latit,
            FROM
                elife-data-warehouse-prod.ods.ride_ride AS t1
                LEFT JOIN elife-data-warehouse-prod.dim.dim_place AS t2 ON t1.from_place_id = t2.id
        ),
        ToPlace AS (
            SELECT
                t1.id AS ride_id,
                t1.to_place_id as end_place_id,
                t2.name AS end_place,
                t2.lng AS longt,
                t2.lat AS latit,
            FROM
                elife-data-warehouse-prod.ods.ride_ride AS t1
                LEFT JOIN elife-data-warehouse-prod.dim.dim_place AS t2 ON t1.to_place_id = t2.id
        ),
        VehicleClass AS (
            SELECT
                t1.id AS ride_id,
                t1.vehicle_class_id as vehicle_class_id,
                t2.name AS vehicle_class,
            FROM
                elife-data-warehouse-prod.ods.ride_ride AS t1
                LEFT JOIN elife-data-warehouse-prod.ods.ride_vehicle_class AS t2 ON t1.vehicle_class_id = t2.id
        ),
        PricingTraining AS (SELECT t0.id       AS ride_id,
                                   t1.id       AS dispatch_id,
                                   t2.trip_type_id,
                                   t2.trip_type,
                                   t1.trip_no,
                                   t3.ride_status_id,
                                   t3.ride_status,
                                   t4.partner_id,
                                   t4.partner,
                                   t0.from_time_str,
                                   t0.from_timezone_str,
                                   t0.to_time_str,
                                   t0.to_timezone_str,
                                   t5.start_place_id,
                                   t5.start_place,
                                   t5.longt    AS start_longt,
                                   t5.latit    AS start_latit,
                                   t6.end_place_id,
                                   t6.end_place,
                                   t6.longt    AS end_longt,
                                   t6.latit    AS end_latit,
                                   t0.distance,
                                   t0.duration,
                                   t7.vehicle_class_id,
                                   t7.vehicle_class,
                                   t0.passenger_count,
                                   t0.luggage_count,
                                   t0.trip_count,
                                   t0.children_count,
                                   t0.infant_count,
                                   t1.amount   as dispatch_amount,
                                   t1.currency as dispatch_currency,

                            FROM `elife-data-warehouse-prod.ods.ride_ride` AS t0
                                     JOIN `elife-data-warehouse-prod.ods.ride_dispatch` AS t1 ON t0.id = t1.ride_id
                                     LEFT JOIN TripType AS t2 ON t0.id = t2.ride_id
                                     LEFT JOIN RideStatus AS t3 ON t0.id = t3.ride_id
                                     LEFT JOIN Partner AS t4 ON t0.id = t4.ride_id
                                     LEFT JOIN FromPlace AS t5 ON t0.id = t5.ride_id
                                     LEFT JOIN ToPlace AS t6 ON t0.id = t6.ride_id
                                     LEFT JOIN VehicleClass AS t7 ON t0.id = t7.ride_id
                            WHERE from_time_str > '2024-01-01'
        )

        SELECT
            t.ride_id,
            t.dispatch_id,
            t.trip_type,
            t.trip_no,
            t.ride_status,
            t.partner,
            t.from_time_str,
            t.from_timezone_str,
            t.to_time_str,
            t.to_timezone_str,
            t.start_place,
            t.start_latit,
            t.start_longt,
            t.end_place,
            t.end_latit,
            t.end_longt,
            t.distance,
            t.duration,
            t.vehicle_class,
            t.passenger_count,
            t.luggage_count,
            t.trip_count,
            t.children_count,
            t.infant_count,
            t.dispatch_amount,
            t.dispatch_currency,

        FROM
            PricingTraining AS t
        WHERE
            from_time_str > '2024-01-01'
        LIMIT
            200
"""

In [ ]:
#| export
def get_dataframe_from_sql(
        credential: Credentials,
        query: str = QUERY_PRICING_TRAINING
) -> pd.DataFrame:
    """
    get dataframe from sql query in BigQuery dialect 
    
    :param
        credential: google.oauth2.service_account.Credentials
        query: string for sql query in BigQuery dialect
    :return: 
    """
    
    df = pandas_gbq.read_gbq(query,credentials=credential)
    
    return df

In [ ]:
# df = get_dataframe_from_sql(QUERY_PRCING_TRAINING,credential)

In [ ]:
# df

In [ ]:
from sqllineage.runner import LineageRunner
#from lineagex.lineagex import lineagex

In [ ]:
sql =   """
        WITH
        TripTypeID AS (
            SELECT
                t1.ride_id,
                CASE
                    WHEN t2.trip_no = t1.trip_no THEN t2.trip_type
                    ELSE NULL
                END AS trip_type_id,
            FROM
                `elife-data-warehouse-prod.ods.ride_dispatch` AS t1
                JOIN `elife-data-warehouse-prod.ods.ride_trip` AS t2 ON t1.ride_id = t2.ride_id
        ),
        TripType AS (
            SELECT
                t1.ride_id,
                t1.trip_type_id,
                t2.name AS trip_type,
            FROM
                TripTypeID AS t1
                LEFT JOIN `elife-data-warehouse-prod.ods.ride_enum AS` t2 ON t1.trip_type_id = t2.id
        ),
        RideStatus AS (
            SELECT
                t1.id AS ride_id,
                t1.stat AS ride_status_id,
                t2.name AS ride_status,
            FROM
                `elife-data-warehouse-prod.ods.ride_ride` AS t1
                LEFT JOIN `elife-data-warehouse-prod.ods.ride_enum` AS t2 ON t1.stat = t2.id
        ),
        PartnerID AS (
            SELECT
                t1.id AS ride_id,
                CASE
                    WHEN t2.id = t1.partner_tran_id THEN t2.partner_id
                    ELSE NULL
                END AS partner_id,
            FROM
                `elife-data-warehouse-prod.ods.ride_ride` AS t1
                LEFT JOIN `elife-data-warehouse-prod.ods.ride_partner_tran` AS t2 ON t1.partner_tran_id = t2.id
        ),
        Partner AS (
            SELECT
                t1.ride_id,
                t1.partner_id,
                t2.name AS partner,
            FROM
                PartnerID AS t1
                LEFT JOIN `elife-data-warehouse-prod.ods.ride_partner` AS t2 ON t1.partner_id = t2.id
        ),
        FromPlace AS (
            SELECT
                t1.id AS ride_id,
                t1.from_place_id as start_place_id,
                t2.name AS start_place,
                t2.lng AS longt,
                t2.lat AS latit,
            FROM
                `elife-data-warehouse-prod.ods.ride_ride` AS t1
                LEFT JOIN `elife-data-warehouse-prod.dim.dim_place` AS t2 ON t1.from_place_id = t2.id
        ),
        ToPlace AS (
            SELECT
                t1.id AS ride_id,
                t1.to_place_id as end_place_id,
                t2.name AS end_place,
                t2.lng AS longt,
                t2.lat AS latit,
            FROM
                `elife-data-warehouse-prod.ods.ride_ride` AS t1
                LEFT JOIN `elife-data-warehouse-prod.dim.dim_place` AS t2 ON t1.to_place_id = t2.id
        ),
        VehicleClass AS (
            SELECT
                t1.id AS ride_id,
                t1.vehicle_class_id as vehicle_class_id,
                t2.name AS vehicle_class,
            FROM
                `elife-data-warehouse-prod.ods.ride_ride` AS t1
                LEFT JOIN `elife-data-warehouse-prod.ods.ride_vehicle_class` AS t2 ON t1.vehicle_class_id = t2.id
        ),
        PricingTraining AS (SELECT t0.id       AS ride_id,
                                   t1.id       AS dispatch_id,
                                   t2.trip_type_id,
                                   t2.trip_type,
                                   t1.trip_no,
                                   t3.ride_status_id,
                                   t3.ride_status,
                                   t4.partner_id,
                                   t4.partner,
                                   t0.from_time_str,
                                   t0.from_timezone_str,
                                   t0.to_time_str,
                                   t0.to_timezone_str,
                                   t5.start_place_id,
                                   t5.start_place,
                                   t5.longt    AS start_longt,
                                   t5.latit    AS start_latit,
                                   t6.end_place_id,
                                   t6.end_place,
                                   t6.longt    AS end_longt,
                                   t6.latit    AS end_latit,
                                   t0.distance,
                                   t0.duration,
                                   t7.vehicle_class_id,
                                   t7.vehicle_class,
                                   t0.passenger_count,
                                   t0.luggage_count,
                                   t0.trip_count,
                                   t0.children_count,
                                   t0.infant_count,
                                   t1.amount   as dispatch_amount,
                                   t1.currency as dispatch_currency,

                            FROM `elife-data-warehouse-prod.ods.ride_ride` AS t0
                                     JOIN `elife-data-warehouse-prod.ods.ride_dispatch` AS t1 ON t0.id = t1.ride_id
                                     LEFT JOIN TripType AS t2 ON t0.id = t2.ride_id
                                     LEFT JOIN RideStatus AS t3 ON t0.id = t3.ride_id
                                     LEFT JOIN Partner AS t4 ON t0.id = t4.ride_id
                                     LEFT JOIN FromPlace AS t5 ON t0.id = t5.ride_id
                                     LEFT JOIN ToPlace AS t6 ON t0.id = t6.ride_id
                                     LEFT JOIN VehicleClass AS t7 ON t0.id = t7.ride_id
                            WHERE from_time_str > '2024-01-01'
        )

        SELECT
            t.ride_id,
            t.dispatch_id,
            t.trip_type,
            t.trip_no,
            t.ride_status,
            t.partner,
            t.from_time_str,
            t.from_timezone_str,
            t.to_time_str,
            t.to_timezone_str,
            t.start_place,
            t.start_latit,
            t.start_longt,
            t.end_place,
            t.end_latit,
            t.end_longt,
            t.distance,
            t.duration,
            t.vehicle_class,
            t.passenger_count,
            t.luggage_count,
            t.trip_count,
            t.children_count,
            t.infant_count,
            t.dispatch_amount,
            t.dispatch_currency,

        FROM
            PricingTraining AS t
        WHERE
            from_time_str > '2024-01-01'
        LIMIT
            200
        """

In [ ]:
# result = LineageRunner("../data/pricing_training_bigquery.sql", dialect="bigquery")
result = LineageRunner(sql, dialect="bigquery")
#from lineagex.example import example
#example("dependency_example")
#lineagex(sql="../data/pricing_training_bigquery.sql", target_schema="schema1", search_path_schema="schema1, public")

In [ ]:
print(result)

In [ ]:
#| hide
import nbdev; nbdev.nbdev_export()